#--------------------------------------------------------------------
############################# RL config #############################
#--------------------------------------------------------------------
# only for DDPG, TD3 or SAC

#------------- parameters common to DDPG, TD3 and SAC ---------------
#GAME : "flatplate"
GAME : "STARCCMexternalfiles"

MEMORY_CAPACITY : 500000        # for the Replay Memory
BATCH_SIZE : 64
GAMMA : 0.99                    # discount factor
TAU : 0.005                     # update parameter of the target network

ACTION_SIGMA : 0                # additional noise (between chosen and actual action)

MAX_EPISODES : 2             # number of training episodes
MAX_STEPS : 10                 # max steps per episode

# saving and plotting parameters
FREQ_PLOT : 5
FREQ_EVAL : 25
FREQ_SAVE : 250


#-------------- parameters used only by DDPG and TD3 ----------------
HIDDEN_LAYERS : [32, 32, 32]    # NN size
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001

EXPLO_SIGMA : 0.05              # exploration noise


#------------------- parameters used only by TD3 --------------------
# next 2 parameters are set according to the founding paper
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5


#------------------- parameters used only by SAC --------------------
HIDDEN_VALUE_LAYERS : [32, 32, 32]
HIDDEN_Q_LAYERS : [32, 32, 32]
HIDDEN_PI_LAYERS : [32, 32]

VALUE_LR : 0.001
SOFTQ_LR : 0.001
ACTOR_LR : 0.001

AUTO_ALPHA : True
ALPHA_LR : 0.001


#--------------------------------------------------------------------
############################ CFD config #############################
#--------------------------------------------------------------------
DELTA_TIME : 0.0005             # time step
POINTB_CHANGE : 200000          # change B every POINTB_CHANGE episodes

# initial position
XA : 0.0
YA : 0.0
UA : 3.1333
VA : 0.0

# target position, B must be at most 10 deg from the horizontal axis with respect to A
XB : -0.02
YB : 0.005
